[server]
headless = true
port = 7860
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
base = "light"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[global]
logLevel = "error"
disableWatchdogWarning = true
developmentMode = false

[runner]
magicEnabled = false
installTracer = false
fixMatplotlib = false

[logger]
level = "error"
